### ISSUE TITLE
Cannot download the datasets

### ISSUE THREAD

**Issue by mnunes** [okfn-brasil/serenata-toolbox#183]
I installed `serenata-toolbox` module. The module and its dependencies are all up-to-date. I can import the module without any problem. However, when I try to use the `Datasets` function, I get the following error:

    >>> datasets = Datasets('data/')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python3.6/site-packages/serenata_toolbox/datasets/__init__.py", line 54, in __init__
        self.remote = RemoteDatasets()
      File "/usr/local/lib/python3.6/site-packages/serenata_toolbox/datasets/remote.py", line 18, in __init__
        'region_name': config('AMAZON_REGION'),
      File "/usr/local/lib/python3.6/site-packages/decouple.py", line 197, in __call__
        return self.config(*args, **kwargs)
      File "/usr/local/lib/python3.6/site-packages/decouple.py", line 85, in __call__
        return self.get(*args, **kwargs)
      File "/usr/local/lib/python3.6/site-packages/decouple.py", line 70, in get
        raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
    decouple.UndefinedValueError: AMAZON_REGION not found. Declare it as envvar or define a default value.

It seems I need some Amazon (is it some AWS stuff?) credential, but I have no idea on how to get one. Is it free? Is there a website where I can get it?

I am using python 3.6.4 on macOS 10.13.3:

    $ python
    Python 3.6.4 (default, Mar  9 2018, 23:15:03)
    [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.

**Comment by cuducos** [comment]
Many thanks for reporting the bug, @mnunes. Recently we made some changes, there are some undocumented stuff and probably some nasty bugs. I'm gonna take a closer look today.
